### ISSUE TITLE
Phoenix Reborn Discontinued?

### ISSUE THREAD

**Issue by GhostMaree** [Kierze/Phoenix-Reborn-source-AS3-#1]
question.

**Comment by Kierze** [comment]
@GhostMaree this is their newest source, but they stopped coding it like a few weeks ago. It has loads of really cool things that you could check out

**Comment by GhostMaree** [comment]
ok

**Comment by GhostMaree** [comment]
any new server come in future :) ?

**Comment by Kierze** [comment]
@GhostMaree i am done with servers, but you are free to use this source since it has some cool stuff in it ;)

**Comment by Versified** [comment]
They stopped working on it time ago 😆
